# Question 4.23

# Part a)
# THE PROBABILITY A RANDOMLY SELECTED GOVERNMENT EMPLOYEE WITH AN ADVANCED COLLEGE DEGREE ACCEPTS A PROMOTION IS 74.3%
prob_accept <- (743 / 1000) * 100
print(prob_accept)

# Part b)
# THE PROBABILITY A RANDOMLY SELECTED GOVERNMENT EMPLOYEE WITH AN ADVANCED COLLEGE DEGREE DOES NOT ACCEPT A PROMOTION IS 25.7%
prob_reject <- (257 / 1000) * 100
print(prob_reject)

# Part c)
# THE PROBABILITY THAT A RANDOMLY SELECTED GOVERNMENT EMPLOYEE HAVING AN ADVANCED COLLEGE DEGREE HAS A SPOUSE WITH A PROFESSIONAL POSITION IS 46%
prob_professional_spouse <- (460 / 1000) * 100
print(prob_professional_spouse)