# Question 4.16

# Part b)
# THE PROBABLITY OF OCCURANCE THAT A DONOR WILL BE WHITE WITH TYPE-O BLOOD IS 44.88778%
prob_white_typeO <- (0.36 / (0.36 + 0.322 + 0.088 + 0.032)) * 100
print(prob_white_typeO)

# Part c)
# THE PROBABILITY A DONOR WILL HAVE TYPE-O BLOOD IS 46.2%
prob_typeO <- (0.36 + 0.07 + 0.017 + 0.015) * 100
print(prob_typeO)
# BECAUSE THE PROBABILITY OF THESE TWO EVENTS ARE DIFFERENT THEY ARE NOT INDEPENDANT

# Part d)
# THE EVENT OF A DONOR BEING WHITE AND HAVING TYPE-O BLOOD ARE NOT MUTUALLY EXLUSIVE