# QUESTION 5.34

# Part a)
# BECAUSE THE SAMPLE_MEAN IS NOT GIVEN WE CANNOT SUPPORT OR REJECT THE NULL HYPOTHESIS, HOWEVER IF THE T-TEST-STATISTIC VALUE IS LESS THAN OR EQUAL TO -1.812461 WE CAN REJECT HTE NULL HYPOTHESIS
confidence <- 0.05
sample <- 11
t_crit <- qt(p=confidence,df=sample-1)

# Part b)
# BECAUSE THE SAMPLE_MEAN IS NOT GIVEN WE CANNOT SUPPORT OR REJECT THE NULL HYPOTHESIS, HOWEVER IF THE T-TEST-STATISTIC VALUE IS GREATER THAN OR EQUAL TO 2.085963 WE CAN REJECT HTE NULL HYPOTHESIS
confidence <- 0.025
sample <- 21
t_crit <- -1*qt(p=confidence,df=sample-1)